#! /bin/bash

echo "Hello World!"
printf "Hello World! from printf statement"

input="Pre filled text"

printf '$input'

read input

printf "$input"
# this code outputs to output.txt
echo "This is coming from my script" > output.txt
echo $input >> output.txt
